name: gammapy-fermi-lat-data
dependencies:
  - python==3.5
  - cython==0.25
  - numpy==1.11
  - scipy>=0.18
  - astropy==1.2
  - pip:
    - healpy==1.10.3
    - git+https://github.com/gammapy/gammapy.git#egg=gammapy
