# Fermi dataset entry file
# The file has to be kept in sync with fermi_3fhl_data_prepare.sh
name : 3FHL

filenames:
  events    : fermi_3fhl_events.fits.gz
  exposure  : fermi_3fhl_exposure_cube_hpx.fits.gz
  psf       : fermi_3fhl_psf_gc.fits.gz
  livetime  : fermi_3fhl_livetime_cube.fits.gz
  counts    : fermi_3fhl_counts_cube_hpx.fits.gz
  isodiff   : ../isodiff/iso_P8R2_SOURCE_V6_v06.txt
  bkg_norm  : bkg_norm/bkg_norm_image_hpx.fits.gz
